### ISSUE TITLE
Automatic Model Checkpoint Push

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#154]
A utility that will automatically push a model's EMA weights to a given endpoint when a Trainers `.save` is called could be really helpful for increasing the autonomy and decreasing reliance on wandb.

This could take on the form of the Tracker's abstract wrapper where you might have a `LocalSave`, `WandbSave`, `HuggingFaceSave`, etc.

This might be a _good first issue_ if someone wants to jump in and tackle it?

**Comment by Veldrovive** [comment]
This would be a great feature to have. Basically what it comes down to is making trackers more flexible. At the moment you can specify where to load from separately from where logs and checkpoints are stored, but logs and checkpoints must be saved in the same place. Once save, load, and log can all push to use different data locations it will be good.

In order to do this, I would suggest using the same pattern that is used for loading. Instead of having a separate save method for each tracker, have only one on the base class which uses some key from the config to specify the source and the rest of the keys in that section as kwargs.

It might also be nice to allow a user to pass a custom save and load function when creating the tracker so that if they want to house their checkpoints somewhere else they can do so. Maybe if you specify the save source as `custom` you could then substitute your own method in the initializer.
