### ISSUE TITLE
hi, can u make it able to train?

### ISSUE THREAD

**Issue by jinfagang** [lucidrains/DALLE2-pytorch#4]
Dude, I have follow u for a long time. Literally you always chasing something hot and edge, but just create a git repo can not able to train or inference with only some READMEs with citations.

Can u just focus on something and make it able to train? I really want see some deeper work and really appreciated your open source work.

**Comment by lucidrains** [comment]
Sure I'll try

**Comment by lucidrains** [comment]
Sure.. I do plenty of training for consulting work. I need to live too

github.com/enformer-pytorch

**Comment by lucidrains** [comment]
But thanks for the appreciation :)

**Comment by lucidrains** [comment]
Please join eleuther.ai, which I've been a part of since the beginning, it you wish to contribute

**Comment by josephrocca** [comment]
@lucidrains I just wanted to say that I hope you disregard this advice 😅 I think you're spending your time well. The reason I and many others follow you is specifically *because* you are implementing the latest research ("hot and edge", as jinfagang put it) in an easy to read and use manner. Of course, if your contracts allow you to release some pre-trained models too then that's a wonderful bonus :)

**Comment by lucidrains** [comment]
@josephrocca thank you Joseph, that's exactly what i wanted to hear :) (but i need to continue to keep my mind open and hear criticism as well from time to time)
