### ISSUE TITLE
Epochs for Laion Dataset

### ISSUE THREAD

**Issue by Deadsec69** [lucidrains/DALLE2-pytorch#65]
how much epochs will it take to train on laion dataset.I am trying to train it also its taking 25 ms on one full iteration is it expected?

**Comment by rom1504** [comment]
What are you training?
The prior or the decoder?
What model size ?

Small prior models may train in a few hours on some 100M samples on one GPU

If you mean the full scale models that will probably take some 100000 GPU hours.

Pick a reasonable goal then try to achieve that. 
Training a small decoder might be useful at this point since many people are already training prior models.
